name: Auto push to develop-in-home on develop update

on:
     push:
         branches:
             - develop

jobs:
     rebase-in-home:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
               uses: actions/checkout@v1 
             - name: Step one
               run: |
                 echo "branch_one=develop" >> $GITHUB_ENV
                 echo "branch_two=develop_test" >> $GITHUB_ENV
             - name: Rebase in-home
               run: |
                 git checkout env.branch_two
                 git rebase origin/evn.branch_one
             - name: Push rebased in-home
               uses: ad-m/github-push-action@master
               with:
                   branch: env.branch_two
                   github_token: ${{ secrets.GITHUB_TOKEN }}
