name: Auto push to develop-in-home on develop update

IN_HOME_BRANCH="develop_test"

DEVELOP_BRANCH="develop"

on:
     push:
         branches:
             - "$DEVELOP_BRANCH"

jobs:
     rebase-in-home:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
               uses: actions/checkout@v1 
             - name: Rebase in-home
               run: |
                 git checkout "$IN_HOME_BRANCH"
                 git rebase origin/develop
             - name: Push rebased in-home
               uses: ad-m/github-push-action@master
               with:
                   branch: "$IN_HOME_BRANCH"
                   github_token: ${{ secrets.GITHUB_TOKEN }}
